### ISSUE TITLE
Not build with kernel 5.8.3 have bug

### ISSUE THREAD

**Issue by micron10** [hamadmarri/cachy-sched#1]
Hi Hamad
I try to build with latest kernel 5.8.3 but have a small problem
please see log:

CC      kernel/bpf/tnum.o
In file included from ./arch/x86/include/asm/current.h:5,
                 from ./include/linux/sched.h:12,
                 from kernel/sched/sched.h:5,
                 from kernel/sched/fair.c:23:
kernel/sched/fair.c: In function 'pick_next_task_fair':
kernel/sched/fair.c:6218:17: error: implicit declaration of function 'check_cfs_rq_runtime'; did you mean 'init_cfs_rq_runtime'? [-Werror=implicit-function-declaration]
 6218 |    if (unlikely(check_cfs_rq_runtime(cfs_rq))) {
      |                 ^~~~~~~~~~~~~~~~~~~~
./include/linux/compiler.h:78:42: note: in definition of macro 'unlikely'
   78 | # define unlikely(x) __builtin_expect(!!(x), 0)
      |                                          ^
kernel/sched/fair.c:6228:8: error: implicit declaration of function 'pick_next_entity'; did you mean 'set_next_entity'? [-Werror=implicit-function-declaration]
 6228 |   se = pick_next_entity(cfs_rq, curr);
      |        ^~~~~~~~~~~~~~~~
      |        set_next_entity
kernel/sched/fair.c:6228:6: warning: assignment to 'struct sched_entity *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
 6228 |   se = pick_next_entity(cfs_rq, curr);
      |      ^
  CC      kernel/sched/wait_bit.o
At top level:
kernel/sched/fair.c:2844:13: warning: 'update_scan_period' defined but not used [-Wunused-function]
 2844 | static void update_scan_period(struct task_struct *p, int new_cpu)
      |             ^~~~~~~~~~~~~~~~~~

**Comment by hamadmarri** [comment]
Hi Micron,

I haven't yet made the patch working on 5.8.3. I believe they have done some changes on the scheduler in 5.8.3. You could try it on version 5.8 
https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.8.tar.xz
Please let me know if you have any issues with 5.8.

It seems to me that 5.7.10 kernel version has a better performance than 5.8 (with and without the cachy patch), you might find 5.7.10 faster than 5.8.

I will try to make a patch for 5.8.3 
Thank you

**Comment by micron10** [comment]
i will try 5.7 kernel if have news with patch update for 5.8 kernel please
write my

**Comment by thor2002ro** [comment]
compiles and works great on 5.8.3.... probably didnt  disable FAIR_GROUP_SCHED and NUMA in config

**Comment by hamadmarri** [comment]
Hi thor2002ro,

I already added the disable FAIR_GROUP_SCHED and NUMA changes in patch 5.8. It should be disabled automatically when applying the patch.

**Comment by hamadmarri** [comment]
Hi @micron10,

Could you please attach the output of patch command. And also the .config file.  Did you downloaded the full cachy tree kernel or you downloaded the kernel from kernel.org and patched it?

**Comment by micron10** [comment]
Hi
sorry for the late reply
when disable Cgroup and Numa build is fine without any problem.
But i run on server not in desktop pc for game.
On server for routing this sched is not ok.
Server is overload and i remove patch for now.

Martin

**Comment by Vistaus** [comment]
Doesn't work with 5.8 from the 5.8 branch of this repo either:

`$ make -j3                                                                                                       23s 927ms → 2 
scripts/kconfig/conf  --syncconfig Kconfig
  DESCEND  objtool
  CALL    scripts/atomic/check-atomics.sh
  CC      arch/x86/kernel/asm-offsets.s
  UPD     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
  CC      init/main.o
  AS      arch/x86/entry/entry_64.o
  CC      kernel/sched/core.o
  AS      arch/x86/entry/thunk_64.o
  CC      arch/x86/entry/syscall_64.o
  CC      arch/x86/entry/common.o
  CHK     include/generated/compile.h
  CC      init/do_mounts.o
  CC      arch/x86/entry/vdso/vma.o
  CC      init/do_mounts_initrd.o
  CC      arch/x86/entry/vdso/vclock_gettime.o
  CC      init/do_mounts_md.o
  CC      arch/x86/entry/vdso/vgetcpu.o
  X32     arch/x86/entry/vdso/vclock_gettime-x32.o
  X32     arch/x86/entry/vdso/vgetcpu-x32.o
  AS      arch/x86/entry/vdso/vdso32/sigreturn.o
  CC      arch/x86/entry/vdso/vdso32/vclock_gettime.o
  CC      init/initramfs.o
  CC      kernel/sched/loadavg.o
  VDSO    arch/x86/entry/vdso/vdso64.so.dbg
  VDSO    arch/x86/entry/vdso/vdsox32.so.dbg
  VDSO    arch/x86/entry/vdso/vdso32.so.dbg
  OBJCOPY arch/x86/entry/vdso/vdso64.so
  OBJCOPY arch/x86/entry/vdso/vdsox32.so
  OBJCOPY arch/x86/entry/vdso/vdso32.so
  VDSO2C  arch/x86/entry/vdso/vdso-image-64.c
  VDSO2C  arch/x86/entry/vdso/vdso-image-x32.c
  VDSO2C  arch/x86/entry/vdso/vdso-image-32.c
  CC      arch/x86/entry/vdso/vdso-image-64.o
  CC      arch/x86/entry/vdso/vdso-image-x32.o
  CC      arch/x86/entry/vdso/vdso-image-32.o
  CC      init/init_task.o
  AR      arch/x86/entry/vdso/built-in.a
  CC      arch/x86/entry/vsyscall/vsyscall_64.o
  CC      kernel/sched/clock.o
  CC      init/version.o
  AR      arch/x86/entry/vsyscall/built-in.a
  AS      arch/x86/entry/entry_64_compat.o
  AR      init/built-in.a
  CC      kernel/power/qos.o
  CC      arch/x86/entry/syscall_32.o
  CC      kernel/sched/cputime.o
  CC      arch/x86/entry/syscall_x32.o
  CC      kernel/power/main.o
  AR      arch/x86/entry/built-in.a
  CC      arch/x86/events/core.o
  CC      kernel/sched/idle.o
  CC      kernel/power/console.o
  CC      kernel/power/process.o
  CC      kernel/sched/fair.o
  CC      arch/x86/events/amd/core.o
  CC      kernel/power/suspend.o
In file included from ./arch/x86/include/asm/current.h:5,
                 from ./include/linux/sched.h:12,
                 from kernel/sched/sched.h:5,
                 from kernel/sched/fair.c:23:
kernel/sched/fair.c: In function ‘pick_next_task_fair’:
kernel/sched/fair.c:6199:17: error: implicit declaration of function ‘check_cfs_rq_runtime’; did you mean ‘init_cfs_rq_runtime’? [-Werror=implicit-function-declaration]
 6199 |    if (unlikely(check_cfs_rq_runtime(cfs_rq))) {
      |                 ^~~~~~~~~~~~~~~~~~~~
./include/linux/compiler.h:78:42: note: in definition of macro ‘unlikely’
   78 | # define unlikely(x) __builtin_expect(!!(x), 0)
      |                                          ^
kernel/sched/fair.c:6209:8: error: implicit declaration of function ‘pick_next_entity’; did you mean ‘set_next_entity’? [-Werror=implicit-function-declaration]
 6209 |   se = pick_next_entity(cfs_rq, curr);
      |        ^~~~~~~~~~~~~~~~
      |        set_next_entity
kernel/sched/fair.c:6209:6: warning: assignment to ‘struct sched_entity *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 6209 |   se = pick_next_entity(cfs_rq, curr);
      |      ^
  CC      arch/x86/events/amd/uncore.o
  CC      kernel/power/hibernate.o
  CC      arch/x86/events/amd/ibs.o
  CC      arch/x86/events/amd/iommu.o
  CC      kernel/power/snapshot.o
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:281: kernel/sched/fair.o] Error 1
make[1]: *** [scripts/Makefile.build:497: kernel/sched] Error 2
make[1]: *** Waiting for unfinished tasks...
  CC      arch/x86/xen/enlighten.o
  AR      arch/x86/events/amd/built-in.a
  CC      arch/x86/events/msr.o
  CC      arch/x86/xen/mmu.o
  CC      arch/x86/events/intel/core.o
  CC      kernel/power/swap.o
  CC      arch/x86/xen/time.o
  CC      arch/x86/xen/grant-table.o
  CC      kernel/power/user.o
  CC      arch/x86/events/intel/bts.o
  CC      arch/x86/xen/suspend.o
  CC      kernel/power/wakelock.o
  CC      arch/x86/events/intel/ds.o
  CC      arch/x86/xen/enlighten_hvm.o
  CC      kernel/power/poweroff.o
  CC      kernel/power/energy_model.o
  CC      arch/x86/xen/mmu_hvm.o
  AR      kernel/power/built-in.a
make: *** [Makefile:1756: kernel] Fout 2
make: *** Wachten op onvoltooide taken...
  CC      arch/x86/xen/suspend_hvm.o
  CC      arch/x86/events/intel/knc.o
  CC      arch/x86/events/zhaoxin/core.o
  CC      arch/x86/xen/platform-pci-unplug.o
  CC      arch/x86/events/intel/lbr.o
  CC      arch/x86/xen/setup.o
  AR      arch/x86/events/zhaoxin/built-in.a
  CC      arch/x86/platform/pvh/enlighten.o
  AR      arch/x86/platform/pvh/built-in.a
  CC [M]  arch/x86/events/rapl.o
  CC      arch/x86/events/intel/p4.o
  CC      arch/x86/xen/apic.o
  CC      arch/x86/xen/pmu.o
  CC      arch/x86/events/intel/p6.o
  CC      arch/x86/events/intel/pt.o
  CC      arch/x86/xen/suspend_pv.o
  CC      arch/x86/xen/p2m.o
  CC      arch/x86/events/intel/uncore.o
  CC      arch/x86/hyperv/hv_init.o
  CC      arch/x86/xen/enlighten_pv.o
  CC      arch/x86/hyperv/mmu.o
  CC      arch/x86/events/intel/uncore_nhmex.o
  CC      arch/x86/xen/mmu_pv.o
  CC      arch/x86/hyperv/nested.o
  CC      arch/x86/events/intel/uncore_snb.o
  CC      arch/x86/hyperv/hv_apic.o
  CC      arch/x86/events/intel/uncore_snbep.o
arch/x86/hyperv/hv_apic.c: In function ‘hv_send_ipi_mask_allbutself’:
arch/x86/hyperv/hv_apic.c:236:1: warning: the frame size of 1032 bytes is larger than 1024 bytes [-Wframe-larger-than=]
  236 | }
      | ^
  CC      arch/x86/hyperv/hv_spinlock.o
  AR      arch/x86/hyperv/built-in.a
  CC      arch/x86/xen/irq.o
  CC      arch/x86/realmode/init.o
  CC      arch/x86/xen/multicalls.o
  CC [M]  arch/x86/events/intel/cstate.o
  AR      arch/x86/realmode/built-in.a
  AS      arch/x86/xen/xen-asm.o
  AR      arch/x86/events/intel/built-in.a
  LD [M]  arch/x86/events/intel/intel-cstate.o
  AR      arch/x86/events/built-in.a
  AS      arch/x86/xen/xen-asm_64.o
  CC      arch/x86/xen/enlighten_pvh.o
  AS      arch/x86/kernel/head_64.o
  CC      arch/x86/mm/init.o
  CC      arch/x86/kernel/head64.o
  CC      arch/x86/xen/trace.o
  CC      arch/x86/kernel/ebda.o
  CC      arch/x86/mm/init_64.o
  LDS     arch/x86/kernel/vmlinux.lds
  CC      arch/x86/kernel/process_64.o
  CC      arch/x86/xen/smp.o
  CC      arch/x86/kernel/signal.o
  CC      arch/x86/mm/fault.o
  CC      arch/x86/xen/smp_pv.o
  CC      arch/x86/kernel/signal_compat.o
  CC      arch/x86/kernel/traps.o
  CC      arch/x86/xen/smp_hvm.o
  CC      arch/x86/mm/ioremap.o
  CC      arch/x86/xen/spinlock.o
  CC      arch/x86/kernel/idt.o
  CC      arch/x86/mm/extable.o
  CC      arch/x86/xen/vga.o
  CC      arch/x86/kernel/irq.o
  CC      arch/x86/xen/pci-swiotlb-xen.o
  CC      arch/x86/mm/mmap.o
  CC      arch/x86/xen/efi.o
  CC      arch/x86/mm/pgtable.o
  CC      arch/x86/kernel/irq_64.o
  AR      arch/x86/xen/built-in.a
  CC      arch/x86/mm/physaddr.o
  CC      arch/x86/mm/setup_nx.o
  CC      arch/x86/kernel/dumpstack_64.o
  CC      arch/x86/crypto/crc32c-intel_glue.o
  CC      arch/x86/mm/tlb.o
  CC      arch/x86/kernel/ioport.o
  CC [M]  arch/x86/crypto/glue_helper.o
  CC      arch/x86/mm/cpu_entry_area.o
  CC      arch/x86/kernel/dumpstack.o
  AS [M]  arch/x86/crypto/twofish-x86_64-asm_64.o
  CC [M]  arch/x86/crypto/twofish_glue.o
  CC      arch/x86/mm/maccess.o
  CC      arch/x86/kernel/nmi.o
  CC      arch/x86/mm/pat/set_memory.o
  CC [M]  arch/x86/crypto/twofish_glue_3way.o
  CC [M]  arch/x86/crypto/twofish_avx_glue.o
  CC      arch/x86/kernel/ldt.o
  CC [M]  arch/x86/crypto/serpent_sse2_glue.o
  CC      arch/x86/mm/pat/memtype.o
  CC      arch/x86/kernel/setup.o
  CC [M]  arch/x86/crypto/serpent_avx_glue.o
  CC      arch/x86/mm/pat/memtype_interval.o
  CC [M]  arch/x86/crypto/serpent_avx2_glue.o
  CC      arch/x86/kernel/x86_init.o
  AR      arch/x86/mm/pat/built-in.a
  CC      arch/x86/mm/hugetlbpage.o
  CC [M]  arch/x86/crypto/des3_ede_glue.o
  CC      arch/x86/kernel/i8259.o
  CC      arch/x86/mm/dump_pagetables.o
  CC      arch/x86/kernel/irqinit.o
  CC [M]  arch/x86/crypto/camellia_glue.o
  CC      arch/x86/mm/kmmio.o
  CC      arch/x86/kernel/jump_label.o
  CC [M]  arch/x86/crypto/camellia_aesni_avx_glue.o
  CC      arch/x86/kernel/irq_work.o
  CC      arch/x86/mm/pf_in.o
  CC [M]  arch/x86/crypto/camellia_aesni_avx2_glue.o
  CC      arch/x86/mm/mmio-mod.o
  CC      arch/x86/kernel/probe_roms.o
  CC [M]  arch/x86/crypto/blowfish_glue.o
  CC      arch/x86/mm/pkeys.o
  CC      arch/x86/kernel/sys_ia32.o
  CC [M]  arch/x86/crypto/cast5_avx_glue.o
  CC      arch/x86/mm/kaslr.o
  CC      arch/x86/kernel/sys_x86_64.o
  CC [M]  arch/x86/crypto/cast6_avx_glue.o
  CC      arch/x86/mm/pti.o
  CC      arch/x86/kernel/espfix_64.o
  CC [M]  arch/x86/crypto/aegis128-aesni-glue.o
  CC      arch/x86/mm/mem_encrypt.o
  CC      arch/x86/kernel/ksysfs.o
  CC [M]  arch/x86/crypto/chacha_glue.o
  CC      arch/x86/mm/mem_encrypt_identity.o
  CC      arch/x86/kernel/bootflag.o
  CC [M]  arch/x86/crypto/aesni-intel_glue.o
  AR      arch/x86/mm/built-in.a
  CC      arch/x86/ia32/ia32_signal.o
  CC      arch/x86/kernel/e820.o
  AR      arch/x86/ia32/built-in.a
  CC      arch/x86/kernel/pci-dma.o
  CC [M]  arch/x86/crypto/sha1_ssse3_glue.o
  CC      arch/x86/kernel/quirks.o
  CC [M]  arch/x86/platform/atom/punit_atom_debug.o
  CC [M]  arch/x86/crypto/sha256_ssse3_glue.o
  CC      arch/x86/kernel/topology.o
  CC      arch/x86/platform/efi/quirks.o
  CC      arch/x86/kernel/kdebugfs.o
  CC [M]  arch/x86/crypto/sha512_ssse3_glue.o
  CC      arch/x86/kernel/alternative.o
  CC      arch/x86/platform/efi/efi.o
  CC [M]  arch/x86/crypto/blake2s-glue.o
  CC [M]  arch/x86/crypto/ghash-clmulni-intel_glue.o
  CC      arch/x86/platform/efi/efi_64.o
  CC      arch/x86/kernel/hw_breakpoint.o
  CC [M]  arch/x86/crypto/crc32-pclmul_glue.o
  CC      arch/x86/kernel/tsc.o
  AR      arch/x86/platform/efi/built-in.a
  CC      arch/x86/platform/intel/iosf_mbi.o
  CC [M]  arch/x86/crypto/crct10dif-pclmul_glue.o
  CC [M]  arch/x86/crypto/poly1305_glue.o
  CC      arch/x86/kernel/rtc.o
  AR      arch/x86/platform/intel/built-in.a
  CC      arch/x86/platform/sfi/sfi.o
  AR      arch/x86/platform/sfi/built-in.a
  AR      arch/x86/platform/built-in.a
  CC      arch/x86/kernel/pci-iommu_table.o
  CC      arch/x86/net/bpf_jit_comp.o
  CC [M]  arch/x86/crypto/nhpoly1305-sse2-glue.o
  CC      arch/x86/kernel/process.o
  CC [M]  arch/x86/crypto/nhpoly1305-avx2-glue.o
  CC [M]  arch/x86/crypto/curve25519-x86_64.o
  AR      arch/x86/net/built-in.a
  CC      arch/x86/kernel/fpu/init.o
  CC      arch/x86/kernel/ptrace.o
  AR      arch/x86/crypto/built-in.a
  LD [M]  arch/x86/crypto/twofish-x86_64.o
  LD [M]  arch/x86/crypto/twofish-x86_64-3way.o
  LD [M]  arch/x86/crypto/twofish-avx-x86_64.o
  LD [M]  arch/x86/crypto/serpent-sse2-x86_64.o
  LD [M]  arch/x86/crypto/serpent-avx-x86_64.o
  LD [M]  arch/x86/crypto/serpent-avx2.o
  LD [M]  arch/x86/crypto/des3_ede-x86_64.o
  LD [M]  arch/x86/crypto/camellia-x86_64.o
  LD [M]  arch/x86/crypto/camellia-aesni-avx-x86_64.o
  LD [M]  arch/x86/crypto/camellia-aesni-avx2.o
  LD [M]  arch/x86/crypto/blowfish-x86_64.o
  LD [M]  arch/x86/crypto/cast5-avx-x86_64.o
  LD [M]  arch/x86/crypto/cast6-avx-x86_64.o
  LD [M]  arch/x86/crypto/aegis128-aesni.o
  LD [M]  arch/x86/crypto/chacha-x86_64.o
  LD [M]  arch/x86/crypto/aesni-intel.o
  LD [M]  arch/x86/crypto/sha1-ssse3.o
  LD [M]  arch/x86/crypto/sha256-ssse3.o
  LD [M]  arch/x86/crypto/sha512-ssse3.o
  LD [M]  arch/x86/crypto/blake2s-x86_64.o
  LD [M]  arch/x86/crypto/ghash-clmulni-intel.o
  LD [M]  arch/x86/crypto/crc32-pclmul.o
  LD [M]  arch/x86/crypto/crct10dif-pclmul.o
  LD [M]  arch/x86/crypto/poly1305-x86_64.o
  LD [M]  arch/x86/crypto/nhpoly1305-sse2.o
  LD [M]  arch/x86/crypto/nhpoly1305-avx2.o
  CC      arch/x86/kernel/tls.o
  CC      arch/x86/kernel/fpu/bugs.o
  CC      arch/x86/kernel/fpu/core.o
  CC      arch/x86/kernel/fpu/regset.o
  CC      arch/x86/kernel/fpu/signal.o
  CC      arch/x86/kernel/step.o
  CC      arch/x86/kernel/tboot.o
  CC      arch/x86/kernel/fpu/xstate.o
  CC [M]  arch/x86/kvm/../../../virt/kvm/kvm_main.o
  CC [M]  arch/x86/kvm/../../../virt/kvm/coalesced_mmio.o
  AR      arch/x86/kernel/fpu/built-in.a
  CC      arch/x86/kernel/stacktrace.o
  CC [M]  arch/x86/kvm/../../../virt/kvm/eventfd.o
  CC      arch/x86/kernel/cpu/cacheinfo.o
  CC      arch/x86/kernel/cpu/scattered.o
  CC      arch/x86/kernel/acpi/boot.o
  CC      arch/x86/kernel/cpu/topology.o
  CC      arch/x86/kernel/cpu/common.o
  CC      arch/x86/kernel/acpi/sleep.o
  CC [M]  arch/x86/kvm/../../../virt/kvm/irqchip.o
  AS      arch/x86/kernel/acpi/wakeup_64.o
  CC      arch/x86/kernel/acpi/apei.o
  CC      arch/x86/kernel/cpu/match.o
  CC      arch/x86/kernel/cpu/bugs.o
  CC [M]  arch/x86/kvm/../../../virt/kvm/vfio.o
  CC      arch/x86/kernel/acpi/cppc_msr.o
  CC      arch/x86/kernel/acpi/cstate.o
  CC [M]  arch/x86/kvm/../../../virt/kvm/async_pf.o
  AR      arch/x86/kernel/acpi/built-in.a
  CC [M]  arch/x86/kvm/x86.o
  CC      arch/x86/kernel/cpu/aperfmperf.o
  CC      arch/x86/kernel/cpu/umwait.o
  CC [M]  arch/x86/kvm/emulate.o
  CC      arch/x86/kernel/cpu/proc.o
  CC      arch/x86/kernel/cpu/feat_ctl.o
  CC      arch/x86/kernel/cpu/intel.o
  CC      arch/x86/kernel/cpu/intel_epb.o
  CC      arch/x86/kernel/cpu/amd.o
  CC      arch/x86/kernel/cpu/hygon.o
  CC [M]  arch/x86/kvm/i8259.o
  CC      arch/x86/kernel/cpu/centaur.o
  CC      arch/x86/kernel/cpu/zhaoxin.o
  CC      arch/x86/kernel/cpu/mce/core.o
  CC      arch/x86/kernel/cpu/mtrr/mtrr.o
  CC      arch/x86/kernel/cpu/mtrr/if.o
  CC      arch/x86/kernel/cpu/mtrr/generic.o
arch/x86/kernel/cpu/mce/core.o: warning: objtool: mce_panic()+0x118: unreachable instruction
  CC      arch/x86/kernel/cpu/mce/severity.o
  CC      arch/x86/kernel/cpu/mce/genpool.o
  CC      arch/x86/kernel/cpu/mtrr/cleanup.o
  CC [M]  arch/x86/kvm/irq.o
  CC      arch/x86/kernel/cpu/mce/intel.o
  CC      arch/x86/kernel/cpu/mce/amd.o
  AR      arch/x86/kernel/cpu/mtrr/built-in.a
  CC      arch/x86/kernel/reboot.o
  CC [M]  arch/x86/kvm/lapic.o
  CC      arch/x86/kernel/early-quirks.o
  CC      arch/x86/kernel/cpu/mce/threshold.o
  CC [M]  arch/x86/kvm/i8254.o
  CC      arch/x86/kernel/cpu/mce/therm_throt.o
  CC      arch/x86/kernel/smp.o
  CC [M]  arch/x86/kvm/ioapic.o
  CC      arch/x86/kernel/cpu/mce/apei.o
  CC [M]  arch/x86/kvm/irq_comm.o
  CC      arch/x86/kernel/cpu/mce/dev-mcelog.o
  CC      arch/x86/kernel/cpu/microcode/core.o
  CC [M]  arch/x86/kvm/cpuid.o
  CC [M]  arch/x86/kernel/cpu/mce/inject.o
  CC      arch/x86/kernel/cpu/microcode/intel.o
  AR      arch/x86/kernel/cpu/mce/built-in.a
  LD [M]  arch/x86/kernel/cpu/mce/mce-inject.o
  CC      arch/x86/kernel/cpu/resctrl/core.o
  CC      arch/x86/kernel/cpu/microcode/amd.o
  CC [M]  arch/x86/kvm/pmu.o
  CC      arch/x86/kernel/cpu/resctrl/rdtgroup.o
  AR      arch/x86/kernel/cpu/microcode/built-in.a
  CC [M]  arch/x86/kvm/mtrr.o
  CC      arch/x86/kernel/cpu/resctrl/monitor.o
  CC [M]  arch/x86/kvm/hyperv.o
  CC      arch/x86/kernel/cpu/perfctr-watchdog.o
  CC      arch/x86/kernel/cpu/resctrl/ctrlmondata.o
  CC      arch/x86/kernel/smpboot.o
  CC      arch/x86/kernel/cpu/resctrl/pseudo_lock.o
  CC [M]  arch/x86/kvm/debugfs.o
  CC      arch/x86/kernel/tsc_sync.o
  AR      arch/x86/kernel/cpu/resctrl/built-in.a
  CC      arch/x86/kernel/cpu/vmware.o
  CC      arch/x86/kernel/setup_percpu.o
  CC [M]  arch/x86/kvm/mmu/mmu.o
  CC      arch/x86/kernel/cpu/mshyperv.o
  CC [M]  arch/x86/kvm/mmu/page_track.o
  CC      arch/x86/kernel/cpu/acrn.o
  CC      arch/x86/kernel/mpparse.o
  AR      arch/x86/kernel/cpu/built-in.a
  CC [M]  arch/x86/kvm/vmx/vmx.o
  CC      arch/x86/kernel/apic/apic.o
  CC      arch/x86/kernel/apic/vector.o
  CC      arch/x86/kernel/apic/hw_nmi.o
  CC      arch/x86/kernel/ftrace.o
  CC      arch/x86/kernel/apic/io_apic.o
  CC      arch/x86/kernel/apic/msi.o
  CC      arch/x86/kernel/apic/x2apic_phys.o
  CC [M]  arch/x86/kvm/vmx/pmu_intel.o
  CC      arch/x86/kernel/apic/x2apic_cluster.o
  CC [M]  arch/x86/kvm/vmx/vmcs12.o
  CC      arch/x86/kernel/apic/apic_flat_64.o
  CC [M]  arch/x86/kvm/vmx/evmcs.o
  CC [M]  arch/x86/kvm/vmx/nested.o
  AR      arch/x86/kernel/apic/built-in.a
  CC      arch/x86/kernel/crash_core_64.o
  CC      arch/x86/kernel/machine_kexec_64.o
  CC [M]  arch/x86/kvm/svm/svm.o
  CC      arch/x86/kernel/crash.o
  CC      arch/x86/kernel/kexec-bzimage64.o
  CC      arch/x86/kernel/crash_dump_64.o
  CC      arch/x86/kernel/kprobes/core.o
  CC      arch/x86/kernel/kprobes/opt.o
  CC [M]  arch/x86/kvm/svm/pmu.o
  CC [M]  arch/x86/kvm/svm/nested.o
  CC      arch/x86/kernel/kprobes/ftrace.o
  CC [M]  arch/x86/kvm/svm/avic.o
  AR      arch/x86/kernel/kprobes/built-in.a
  CC      arch/x86/kernel/module.o
  CC      arch/x86/kernel/kgdb.o
  CC [M]  arch/x86/kvm/svm/sev.o
  CC      arch/x86/kernel/early_printk.o
  LD [M]  arch/x86/kvm/kvm.o
  CC      arch/x86/kernel/hpet.o
  CC      arch/x86/kernel/amd_nb.o
  LD [M]  arch/x86/kvm/kvm-intel.o
  LD [M]  arch/x86/kvm/kvm-amd.o
  CC      arch/x86/kernel/kvm.o
  CC      arch/x86/kernel/kvmclock.o
  CC      arch/x86/kernel/paravirt.o
  CC      arch/x86/kernel/paravirt_patch.o
  CC      arch/x86/kernel/pvclock.o
  CC      arch/x86/kernel/pmem.o
  CC      arch/x86/kernel/jailhouse.o
  CC      arch/x86/kernel/eisa.o
  CC      arch/x86/kernel/pcspeaker.o
  CC      arch/x86/kernel/check.o
  CC      arch/x86/kernel/pci-swiotlb.o
  CC      arch/x86/kernel/uprobes.o
  CC      arch/x86/kernel/sysfb.o
  CC      arch/x86/kernel/sysfb_efi.o
  CC      arch/x86/kernel/perf_regs.o
  CC      arch/x86/kernel/itmt.o
  CC      arch/x86/kernel/umip.o
  CC      arch/x86/kernel/unwind_orc.o
  CC      arch/x86/kernel/audit_64.o
  CC      arch/x86/kernel/amd_gart_64.o
  CC      arch/x86/kernel/aperture_64.o
  CC      arch/x86/kernel/mmconf-fam10h_64.o
  CC [M]  arch/x86/kernel/msr.o
  CC [M]  arch/x86/kernel/cpuid.o
  AR      arch/x86/kernel/built-in.a
  AR      arch/x86/built-in.a
`

**Comment by hamadmarri** [comment]
Hi Heimen Stoffels,

Which patch file? cachy-5.8.3.patch?
Could you please attach the .config file?

The `kernel/sched/fair.c` shouldn't be compiled in cachy-5.8.3.patch since `cachy.c` is the replacement.


>Doesn't work with 5.8 from the 5.8 branch of this repo either:

Oh I see, for 5.8 branch you need to disable `FAIR_GROUP` and `NUMA` manually

**Comment by Vistaus** [comment]
Hello Hamad,

I did disable those.

**Comment by hamadmarri** [comment]
Could you please confirm with `cat .config | grep FAIR` 
Sometimes you need to touch .config file to let the make knows it's been changed (when renaming .config)

**Comment by Vistaus** [comment]
Hmm, seems like it keeps re-enabling FAIR_GROUP_SCHED in .config. Even touching it doesn't seem to do anything :/

**Comment by hamadmarri** [comment]
Using `make menuconfig`?

**Comment by Vistaus** [comment]
> Using `make menuconfig`?

Yes.

**Comment by hamadmarri** [comment]
Could you please try this patched tree https://github.com/hamadmarri/linux/releases/tag/cachy-5.9-r1

**Comment by Vistaus** [comment]
> Could you please try this patched tree https://github.com/hamadmarri/linux/releases/tag/cachy-5.9-r1

Not working either, but this time because make menuconfig instantly fails:

```
 13:42:33  ~/Downloads/linux-cachy-5.9-r1 
$ make menuconfig                                                                                                    01:42:33  
  HOSTCC  scripts/basic/fixdep
  UPD     scripts/kconfig/mconf-cfg
  HOSTCC  scripts/kconfig/mconf.o
  HOSTCC  scripts/kconfig/lxdialog/checklist.o
  HOSTCC  scripts/kconfig/lxdialog/inputbox.o
  HOSTCC  scripts/kconfig/lxdialog/menubox.o
  HOSTCC  scripts/kconfig/lxdialog/textbox.o
  HOSTCC  scripts/kconfig/lxdialog/util.o
  HOSTCC  scripts/kconfig/lxdialog/yesno.o
  HOSTCC  scripts/kconfig/confdata.o
  HOSTCC  scripts/kconfig/expr.o
  LEX     scripts/kconfig/lexer.lex.c
  YACC    scripts/kconfig/parser.tab.[ch]
  HOSTCC  scripts/kconfig/lexer.lex.o
  HOSTCC  scripts/kconfig/parser.tab.o
  HOSTCC  scripts/kconfig/preprocess.o
  HOSTCC  scripts/kconfig/symbol.o
  HOSTCC  scripts/kconfig/util.o
  HOSTLD  scripts/kconfig/mconf
scripts/kconfig/mconf  Kconfig
sh: 1: ./scripts/gcc-version.sh: Permission denied
init/Kconfig:34: syntax error
init/Kconfig:33: invalid statement
init/Kconfig:34: invalid statement
sh: 1: ./scripts/ld-version.sh: Permission denied
init/Kconfig:39: syntax error
init/Kconfig:38: invalid statement
sh: 1: ./scripts/clang-version.sh: Permission denied
init/Kconfig:49: syntax error
init/Kconfig:48: invalid statement
make[1]: *** [scripts/kconfig/Makefile:29: menuconfig] Fout 1
make: *** [Makefile:606: menuconfig] Fout 2
$
```

**Comment by Vistaus** [comment]
*bump* :)

**Comment by hamadmarri** [comment]
Hi Heimen,

I think you have permissions problem.
Not sure why you have `Permission denied`

I am going to double check if the edited files have different permissions in the repo

**Comment by Vistaus** [comment]
Thans for looking into it! :)

**Comment by hamadmarri** [comment]
Hi Heimen,

From your build errors:
```
sh: 1: ./scripts/gcc-version.sh: Permission denied
sh: 1: ./scripts/ld-version.sh: Permission denied
sh: 1: ./scripts/clang-version.sh: Permission denied

```

I suspect that the problem is related to gcc or clang installation 
Please try to check the current gcc in your machine, it looks like make is not able to reach gcc

**Comment by Vistaus** [comment]
I have no problem compiling other software.

**Comment by Vistaus** [comment]
I now got XanMod-5.9.0-rc3 with Cachy to boot so this is no longer an issue. Thanks for all of your help, though! :)

**Comment by hamadmarri** [comment]
Hi Heimen,

Good to hear it is working, I am compiling XanMod-5.9.0-rc3 right now :+1: :+1:
